# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ZhihuDiary' do
    pod "AFNetworking"
end

target 'ZhihuDiaryTests' do

end

target 'ZhihuDiaryUITests' do

end

